
services:

  db:
    image: postgres:16-alpine
    container_name: app_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      LANG: pl_PL.UTF-8
      LC_ALL: pl_PL.UTF-8
      TZ: Europe/Warsaw
      POSTGRES_INITDB_ARGS: "--locale=pl_PL.UTF-8 --encoding=UTF8"
    command: ["postgres", "-c", "datestyle=ISO,DMY"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10




  web:
    build: .
    container_name: app_web
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        gunicorn article_scraper.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@db:5432/${POSTGRES_DB:-app}}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped

  scraper:
    build: .
    container_name: app_scraper
    command: bash -c "python manage.py scrape"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@db:5432/${POSTGRES_DB:-app}}
      RUN_MIGRATIONS: "1"
      # ⬅️ Jak wyżej — z .env / dj-database-url
    depends_on:
      db:
        condition: service_healthy
    profiles: ["scrape"]                        # ⬅️ Uruchamiaj on-demand: `docker compose run --rm scraper`

volumes:
  pgdata:


