# Generated by Django 5.2.7 on 2025-10-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField()),
                ("content", models.TextField()),
                ("cleaned_content", models.TextField()),
                ("url", models.URLField()),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
