# Generated by Django 5.2.7 on 2025-10-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.TextField(),
        ),
    ]
