# Generated by Django 5.2.7 on 2025-10-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_alter_article_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
